<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Sanjeet3149591" ignored="0" name="Order Flow Test" tests="2" failures="1" timestamp="17 Dec 2018 04:40:08 GMT" time="0.331" errors="0">
  <testcase name="placeNewOrderInPastorWrongJson" time="0.091" classname="com.nagarro.TestCases.PlaceOrderInPastorWrongJson"/>
  <testcase name="placeNewOrderWithAllSameStop" time="0.195" classname="com.nagarro.TestCases.PlaceOrderWithAllSameStop">
    <failure type="java.lang.AssertionError" message="expected [0] but found [20.00]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [20.00]
at com.nagarro.TestCases.PlaceOrderWithAllSameStop.placeNewOrderWithAllSameStop(PlaceOrderWithAllSameStop.java:80)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- placeNewOrderWithAllSameStop -->
</testsuite> <!-- Order Flow Test -->
