<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Sanjeet3149591" name="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture" tests="13" failures="1" timestamp="18 Dec 2018 06:05:31 GMT" time="11.154" errors="0">
  <testcase name="placeNewOrderInPresent" time="3.394" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="cancelOrder" time="0.125" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="fetchTheOrderDetails" time="0.809" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="takeTheOrderDetails" time="0.166" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="CompleteTheOrderDetails" time="0.159" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="takeTheCompletedOrder" time="0.980" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="takeTheCancelledOrder" time="0.843" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="CompleteTheNewOrder" time="0.982" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="CompleteTheOrderAfterCompleted" time="1.078" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="cancelTheOrderAfterCompleted" time="0.911" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="cancelTheOrderAfterCancel" time="0.752" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture">
    <failure type="java.lang.AssertionError" message="Status code is not 422 expected [422] but found [200]">
      <![CDATA[java.lang.AssertionError: Status code is not 422 expected [422] but found [200]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture.CommonUtilityForResponseCode422(TestcasesForOrderPlacedInPresentNFuture.java:294)
at com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture.cancelTheOrderAfterCancel(TestcasesForOrderPlacedInPresentNFuture.java:361)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- cancelTheOrderAfterCancel -->
  <testcase name="CompleteTheOrderAfterCancel" time="0.846" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
  <testcase name="fetchTheOrderDetailsNotCreated" time="0.109" classname="com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture"/>
</testsuite> <!-- com.nagarro.testCases.TestcasesForOrderPlacedInPresentNFuture -->
